FROM node:20-alpine AS front-build

WORKDIR /app

COPY front/package.json front/package-lock.json* ./
RUN npm ci

COPY front/ ./
RUN npm run build

FROM nginx:alpine

COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=front-build /app/dist /usr/share/nginx/html

EXPOSE 80
